version: 2
jobs:
  android:
    docker:
      - image: circleci/android@sha256:9d2e4571898fd9b1dc97bfb9da942aaeea46859eb5b1e4cfc85a44c42733643c
    environment:
      QEMU_AUDIO_DRV: none
      _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xms2048m -Xmx4096m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
          reusable: true  # Deprecated version of above

      - run: mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
      - run: sdkmanager "system-images;android-24;default;armeabi-v7a"
      - run: sdkmanager --licenses
      - run: sudo apt-get update && sudo apt-get install libpulse0
      - run: echo no | avdmanager create avd -n rn-android -f -k "system-images;android-24;default;armeabi-v7a"
      - run: 
          command: emulator -avd rn-android -netdelay none -netspeed full -no-audio -no-window -no-snapshot -use-system-libs -no-boot-anim
          background: true
          timeout: 1200
          no_output_timeout: 20m
      - run: sudo npm install -g react-native-cli
      - run: cd .. && git clone https://github.com/launchdarkly/hello-react-native.git
      - run: cd ../hello-react-native && npm install
      - run: cp -r ../project/ ../hello-react-native/node_modules/launchdarkly-react-native-client-sdk/
      - run: circle-android wait-for-boot
      - run: 
          command: cd ../hello-react-native && react-native run-android
          background: true
          timeout: 1200

  ios:
    macos:
      xcode: "11.4"
    steps:
      - checkout

      - run: xcrun simctl create rn-ios com.apple.CoreSimulator.SimDeviceType.iPhone-X com.apple.CoreSimulator.SimRuntime.iOS-12-2
      - run: xcrun simctl boot rn-ios
      - run: cd .. && git clone https://github.com/launchdarkly/hello-react-native.git
      - run: cd ../hello-react-native && npm install
      - run: sudo npm install -g react-native-cli
      - run: cp -r ../project/ ../hello-react-native/node_modules/launchdarkly-react-native-client-sdk/
      # Newer cocoapods required for following pod install
      - run: sudo gem install cocoapods
      # RN 0.64 has an issue with embedding absolute paths in the cocoapods generated build files, so must regenerate.
      # https://github.com/facebook/react-native/issues/31121
      - run: cd ../hello-react-native/ios && pod install
      - run: cd ../hello-react-native && react-native run-ios --configuration Release --simulator rn-ios

  common:
    docker:
      - image: cimg/node:current
    steps:
      - checkout

      - run: npm install
      - run: mkdir -p reports/jest
      - run:
          command: npm run test:junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "./reports/jest"

      - run: npm run check-typescript

      - store_test_results:
          path: reports

workflows:
  version: 2
  android-ios:
    jobs:
      - common
      - android:
          requires:
            - common
      - ios:
          requires:
            - common
