version: 2.1

orbs:
  android: circleci/android@1.0
  node: circleci/node@4.8.0

aliases:
  - &use_local_sdk
    name: Set hello application to use local SDK and RN version
    command: |
      cd ../hello-react-native
      TEMP_FILE=`mktemp -u` || exit 1
      sed 's/"launchdarkly-react-native-client-sdk" *: *"[^"]*" *, *$/"launchdarkly-react-native-client-sdk": "file:..\/project"\,/' 'package.json' > $TEMP_FILE
      mv $TEMP_FILE 'package.json'

jobs:
  android:
    parameters:
      hello-app-branch:
        type: string

    executor:
      name: android/android-machine
      resource-class: large

    steps:
      - checkout

      - run: cd .. && git clone --depth 1 https://github.com/launchdarkly/hello-react-native.git -b <<parameters.hello-app-branch>>
      - run: *use_local_sdk
      - node/install:
          lts: true
          install-yarn: true
      - run:
          name: Build bundle
          command: |
            cd ../hello-react-native
            npx yarn install
            npx react-native bundle --entry-file index.js --platform android --bundle-output android/main.jsbundle --assets-dest android
      - run:
          name: Setup debug keystore
          command: |
            keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "cn=Unknown, ou=Unknown, o=Unknown, c=Unknown"
            cp debug.keystore ../hello-react-native/android/app/
            mkdir -p ~/.android
            cp debug.keystore ~/.android/
      - run: cd ../hello-react-native/android && ./gradlew packageDebug

  ios:
    parameters:
      hello-app-branch:
        type: string
    macos:
      xcode: "12.4.0"
    steps:
      - checkout
      - run: cd .. && git clone --depth 1 https://github.com/launchdarkly/hello-react-native.git -b <<parameters.hello-app-branch>>
      - run: *use_local_sdk
      - run: cd ../hello-react-native && npx yarn install
      - run:
          name: Build bundle
          command: |
            cd ../hello-react-native
            npx yarn install
            npx react-native bundle --entry-file index.js --platform ios --bundle-output ios/main.jsbundle --assets-dest ios
      - run:
          name: Build application
          command: |
            cd ../hello-react-native/ios
            # Newer cocoapods required for following pod install
            sudo gem install cocoapods
            # RN 0.64 has an issue with embedding absolute paths in the cocoapods generated build files, so must regenerate.
            # https://github.com/facebook/react-native/issues/31121
            pod update
            pod install
            xcodebuild build -workspace HelloReactNative.xcworkspace -configuration Release -scheme HelloReactNative -sdk iphonesimulator -arch x86_64 CODE_SIGN_IDENTITY=

  common:
    docker:
      - image: cimg/node:current
    steps:
      - checkout

      - run: npm install
      - run: mkdir -p reports/jest
      - run:
          command: npm run test:junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "./reports/jest"

      - run: npm run check-typescript

      - store_test_results:
          path: reports

workflows:
  version: 2
  android-ios:
    jobs:
      - common
      - android:
          name: Android + RN 0.63
          hello-app-branch: rn-0.63
          requires:
            - common
      - ios:
          name: iOS + RN 0.63
          hello-app-branch: rn-0.63
          requires:
            - common
      - android:
          name: Android + RN 0.64
          hello-app-branch: rn-0.64
          requires:
            - common
      - ios:
          name: iOS + RN 0.64
          hello-app-branch: rn-0.64
          requires:
            - common
