version: 2

repo:
  public: react-native-client-sdk
  private: react-native-client-sdk-private

publications:
  - url: https://www.npmjs.com/package/launchdarkly-react-native-client-sdk
    description: npm

jobs:
  - docker:
      image: node:16-buster
    template:
      name: npm

documentation:
  gitHubPages: true
  title: LaunchDarkly Client-Side SDK for React Native

sdk:
  displayName: React Native
